owner: gigapipehq
repo: upptime 

sites:
  - name: dev-api
    url: $DEV_API
  - name: dev-auth
    url: $DEV_AUTH
  - name: dev-qryn
    url: $DEV_QRYN
    expectedStatusCodes:
      - 401
  - name: dev-app
    url: $DEV_APP

  - name: us-prod-api
    url: $US_PROD_API
  - name: us-prod-auth
    url: $US_PROD_AUTH
  - name: us-prod-qryn
    url: $US_PROD_QRYN
    expectedStatusCodes:
      - 401
  - name: us-prod-app
    url: $US_PROD_APP

  - name: trials-api
    url: $TRIAL_API
  - name: trials-auth
    url: $TRIAL_AUTH
  - name: trials-qryn
    url: $TRIAL_QRYN
    expectedStatusCodes:
      - 401
  - name: trials-app
    url: $TRIAL_APP
